name: Dependency Updates

on:
  schedule:
    # Run monthly on the 1st at 3 AM UTC
    - cron: '0 3 1 * *'
  workflow_dispatch:

jobs:
  update-dependencies:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install pip-tools
      run: |
        python -m pip install --upgrade pip
        pip install pip-tools

    - name: Backup current requirements
      run: |
        cp requirements.txt requirements.txt.backup

    - name: Check for updates
      run: |
        # Create requirements.in from requirements.txt if it doesn't exist
        if [ ! -f requirements.in ]; then
          # Convert pinned versions to flexible ones
          sed 's/==/>=/' requirements.txt > requirements.in
        fi
        
        # Compile new requirements
        pip-compile --upgrade requirements.in

    - name: Test updated dependencies
      run: |
        pip install -r requirements.txt
        python -m py_compile *.py

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'chore: update dependencies'
        title: 'Automated dependency update'
        body: |
          ## Dependency Update
          
          This PR contains automated dependency updates.
          
          ### Changes
          - Updated packages to their latest compatible versions
          - Verified Python files still compile with new dependencies
          
          ### Testing
          - [x] Python syntax check passed
          - [x] Dependencies install successfully
          
          Please review the changes and test thoroughly before merging.
        branch: automated-dependency-update
        delete-branch: true

  dependabot-auto-merge:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    
    steps:
    - name: Check if PR is from Dependabot
      run: echo "This is a Dependabot PR"
      
    - name: Enable auto-merge for Dependabot PRs
      run: |
        echo "Auto-merge would be enabled for minor/patch updates"
        echo "Major updates require manual review"